name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Client Dependencies
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Install Server Dependencies
        working-directory: ./server
        run: |
          npm install

      - name: Restart The Server
        working-directory: ./server
        run: |
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
